README.md
* update install with instructions on where to install deno and how to quickly get the site built for the first time
=> Update Readme with install instructions

src/libraries/Delfos/PathPlus.md, src/libraries/delfos1/PathPlus.md, src/libraries/delfos1/pulse.md
Automation: Submission PathPlus
=> Submission: PathPlus

src/libraries/yellowafterlife/cmnLoc.md
=> Submission: cmnLoc

src/libraries/Juju Adams/Unity Analytics.md, src/libraries/juju-adams/unity-analytics.md
Automation: Submission Unity Analytics
=> Submission: Unity Analytics

src/technicals/grisgram/QSS - Quick SQL Script.md
Automation: Submission QSS - Quick SQL Script
=> Submission: QSS - Quick SQL Script

src/snippets/Juju Adams/string_split_moreso.md, src/undefineds/coldrock.games / grisgram/git-scripts for Windows.md
Automation: Submission string_split_moreso
=> Submission: string_split_moreso

src/assets/Sidorakh/Progressify.md
Automation: Submission Progressify
=> Submission: Progressify

src/libraries/Sidorakh/Custom Tabs.md
Automation: Submission Custom Tabs
=> Submission: Custom Tabs

src/libraries/YellowAfterlife/winMenu.md
Automation: Submission winMenu
=> Submission: winMenu

src/tutorials/Jordan Guillou/10_levels_of_platformer_jumps.md
Hopefully everything was done right :)
=> Submission of my tutorial for the Cookbook Jam 3

src/tutorials/ThatFirey/githubautobuild.md
Forgot to remove that from the introduction, will add later
=> Removed mentions of Itch.Io in GitHub Actions tutorial

src/undefineds/Tinkerer_Red/JS Promise in GM.md
Automation: Submission JS Promise in GM
=> Submission: JS Promise in GM

src/tools/keeveegames/Shady - GLSL preprocessor for code reuse! Import and inline directives, generate shader variants..md
Automation: Submission Shady - GLSL preprocessor for code reuse! Import and inline directives, generate shader variants.
=> Submission: Shady

src/libraries/sidorakh/uuid.gml.md
Automation: Submission uuid.gml
=> Submission: uuid.gml

src/libraries/sidorakh/GX keyboard_string fix.md
Automation: Submission GX keyboard_string fix
=> Submission: GX keyboard_string fix

src/_includes/css/navbar.css
|---|---|
| ![image](https://github.com/user-attachments/assets/aae88c99-bf24-49a2-8e81-469e9fd70d66) | ![image](https://github.com/user-attachments/assets/99c98edc-2bc2-485f-95e4-5ef166eeea19) |
=> Cleaner line wrapping in the navbar

src/_includes/css/footer.css, src/_includes/css/reset.css, src/_includes/layouts/base.njk
|---|---|
| ![image](https://github.com/user-attachments/assets/42903f70-d8fe-4b1c-8ded-64f44e73cd9c) | ![image](https://github.com/user-attachments/assets/50d32ef7-3a91-4113-8b4c-e17f49e9bac0) |
| ![image](https://github.com/user-attachments/assets/c9a57064-d7c1-441c-a264-9ad25ebc1fce) | ![image](https://github.com/user-attachments/assets/0d17a876-6d6d-4cf4-969f-1488957a940d) |
=> Pin the footer to the bottom of the page

src/_includes/css/tag.css, src/authors.njk
|---|---|
| ![image](https://github.com/user-attachments/assets/e0b3a0af-bd84-4d60-b174-2287d5c49f76) | ![image](https://github.com/user-attachments/assets/97d1c76a-1be8-48ee-ae0c-27cf1211541b) |
=> Nicer vertical spacing in the author list

src/_includes/css/resource-list.css, src/_includes/templates/resourcelist.njk
|---|---|
| ![image](https://github.com/user-attachments/assets/005dc036-dbd5-4902-8215-0ff4cac7d571) | ![image](https://github.com/user-attachments/assets/04d7ffa3-9203-46e1-bb4c-06f99c23081a) |
=> Full size card banners

src/_includes/css/post-list.css
|---|---|
| ![image](https://github.com/user-attachments/assets/5022d8b0-8f88-43ab-9246-75e5d431fb61) | ![image](https://github.com/user-attachments/assets/bee34ac1-a5af-4e37-8612-276b222428f0) |
=> Remove tiny horizontal indent on posts

src/template_generators/search.tmpl.js
Fixes plugins not showing up in the search results.
=> Also search for plugins in the search box

src/libraries/Tinkerer_Red/Emobble - Emoji Support for Scribble.md
Automation: Submission Emobble - Emoji Support for Scribble
=> Submission: Emobble - Emoji Support for Scribble

src/libraries/sdlwdr/RunGML.md
=> Submission: RunGML

src/libraries/zntm/Scunthorpe.md, src/snippets/Tinkerer_Red/GML-Super.md
Automation: Submission GML-Super
=> Submission: GML-Super

src/libraries/NordLandeW/gm-zstd.md
Automation: Submission gm-zstd
=> Submission: gm-zstd
